import { Product, Category, Review } from './types'

export const categories: Category[] = [
  {
    id: '1',
    name: 'Laptops',
    slug: 'laptops',
    image: '/images/categories/laptops.jpg',
  },
  {
    id: '2',
    name: 'Smartphones',
    slug: 'smartphones',
    image: '/images/categories/smartphones.jpg',
  },
  {
    id: '3',
    name: 'Audio',
    slug: 'audio',
    image: '/images/categories/audio.jpg',
  },
  {
    id: '4',
    name: 'Accessories',
    slug: 'accessories',
    image: '/images/categories/accessories.jpg',
  },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'MacBook Pro 14"',
    slug: 'macbook-pro-14',
    description: 'The most powerful MacBook Pro ever is here. With the blazing-fast M3 Pro or M3 Max chip.',
    price: 250000,
    category: categories[0],
    brand: 'Apple',
    stock: 15,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca4?w=800&q=80',
    is_featured: true,
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Sony WH-1000XM5',
    slug: 'sony-wh-1000xm5',
    description: 'Industry-leading noise cancellation optimizing to your environment.',
    price: 45000,
    discount_price: 39999,
    category: categories[2],
    brand: 'Sony',
    stock: 50,
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80',
    is_featured: true,
    rating: 4.9,
    reviewCount: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    description: 'Unleash new ways to create, connect, and more with Galaxy AI.',
    price: 180000,
    category: categories[1],
    brand: 'Samsung',
    stock: 20,
    image: 'https://images.unsplash.com/photo-1610945265078-d86f3d297df5?w=800&q=80',
    is_featured: true,
    rating: 4.7,
    reviewCount: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Dell XPS 15',
    slug: 'dell-xps-15',
    description: 'High-performance laptop with 4K OLED display.',
    price: 210000,
    category: categories[0],
    brand: 'Dell',
    stock: 10,
    image: 'https://images.unsplash.com/photo-1593642632823-8f78536788c6?w=800&q=80',
    is_featured: false,
    rating: 4.6,
    reviewCount: 56,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'iPhone 15 Pro Max',
    slug: 'iphone-15-pro-max',
    description: 'Titanium design, A17 Pro chip, and the most powerful iPhone camera system ever.',
    price: 200000,
    category: categories[1],
    brand: 'Apple',
    stock: 30,
    image: 'https://images.unsplash.com/photo-1695048180490-096876fe83c9?w=800&q=80',
    is_featured: true,
    rating: 4.9,
    reviewCount: 310,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Logitech MX Master 3S',
    slug: 'logitech-mx-master-3s',
    description: 'Performance wireless mouse with 8K DPI tracking.',
    price: 15000,
    category: categories[3],
    brand: 'Logitech',
    stock: 100,
    image: 'https://images.unsplash.com/photo-1605773527852-c546a8584ea3?w=800&q=80',
    is_featured: false,
    rating: 4.8,
    reviewCount: 150,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userId: 'user1',
    rating: 5,
    title: 'Amazing machine!',
    comment: 'The performance is incredible, and the battery life lasts all day.',
    helpful: 12,
    verified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    productId: '1',
    userId: 'user2',
    rating: 4,
    title: 'Great but expensive',
    comment: 'Best laptop I have ever used, but the price is a bit steep.',
    helpful: 5,
    verified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]